#!/usr/bin/env bash
## obfuscate_secrets:: Obfuscate :: Secrets

#
## Initialization :: Variables :: Static

# Template files :: Paths
readonly sr_tf_paths=(../archiso/aanp/airootfs/etc/fwknop/access.conf ../archiso/aanp/airootfs/root/.ssh/authorized_keys)

#
## Initialization :: Variables :: Dynamic

# Variable modification :: Script :: Short name
readonly sr_script_sn="$(basename "${BASH_SOURCE[0]}")"

# Variable modification :: Script :: Resolved absolute path name
readonly sr_script_rapn="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

#
## Preprocess :: Phase 0

# Loop :: Array :: Automated script :: Templates
for sr_template_file in "${sr_tf_paths[@]}"; do
    # Validate :: Automated script template existence
    if [[ ! -e "$sr_script_rapn/$sr_template_file.tmpl" ]]; then
        # Notify :: Validation failure
        printf '%s\n' "FAIL :: Validation :: Template existence :: $sr_script_rapn/$sr_template_file.tmpl :: $sr_script_sn/$LINENO"

        # Action :: Exit ungracefully
        exit 1
    fi

    # Variable modification :: sr_template_file
    unset sr_template_file
done

#
## Preprocess :: Phase 1

# Variable modification :: Secret :: Obfuscated Obfuscated :: OpenSSH :: Public key
readonly secret_al_openssh_pk="$(pass show personal/ssh/ed25519-obfuscated/identity.pub 2> /dev/null)"

# Variable modification :: Secret :: provision :: fwknop :: hmac :: base64
readonly secret_provision_fwknop_hmac_base64="$(pass show svc.vps.domain.tld/provision/fwknop/hmac-base64 2> /dev/null)"

# Variable modification :: Secret :: provision :: fwknop :: rijndael :: base64
readonly secret_provision_fwknop_rijndael_base64="$(pass show svc.vps.domain.tld/provision/fwknop/rijndael-base64 2> /dev/null)"

#
## Preprocess :: Phase 2

# Loop :: Secrets
for secret in $(printf '%s\n' secret_al_openssh_pk secret_provision_fwknop_hmac_base64 secret_provision_fwknop_rijndael_base64); do
    # Validate :: Secret content // Cannot be empty
    if [[ -z "${!secret}" ]]; then
        # Notify :: Empty secret
        printf '%s\n' "FAIL :: Secret not available :: ${secret} :: $sr_script_sn/$LINENO"

        # Action :: Exit ungracefully
        exit 1
    fi
done

#
## Main :: Phase 0

# Loop :: Array :: Automated script :: Templates
for sr_template_file in "${sr_tf_paths[@]}"; do
    # File modification :: Automated script
    sed -e "s/@@secret_al_openssh_pk@@/$secret_al_openssh_pk/g" -e "s#@@secret_provision_fwknop_hmac_base64@@#$secret_provision_fwknop_hmac_base64#g" -e "s#@@secret_provision_fwknop_rijndael_base64@@#$secret_provision_fwknop_rijndael_base64#g" "$sr_script_rapn/$sr_template_file.tmpl" > "$sr_script_rapn/$sr_template_file" || {
        # Notify :: Execution failure
        printf '%s\n' "FAIL :: sed :: $sr_script_rapn/$sr_template_file.tmpl :: $sr_script_sn/$LINENO"

        # Action :: Exit ungracefully
        exit 1
    }

    # Variable modification :: sr_template_file
    unset sr_template_file
done
